name: Check Changed Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changes
        run: |
          # Получаем список изменённых файлов между текущей веткой и базовой
          git fetch origin main
          # Получаем список файлов, изменённых в сравнении с базовой веткой
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          
          echo "$CHANGED_FILES"
          
          # Записываем список в вывод для дальнейшего использования
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Display changed files
        run: |
          echo "Изменённые файлы:"
          echo "${{ steps.changes.outputs.changed_files }}"