name: Simple changed files check

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        run: |
          echo "Changed files between commits:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}